const ICON_ROOT = new URL("./icons/trial/", import.meta.url);

const ICONS = Object.freeze({
  shortsword: "../weapons/shortsword.png",
  piercing_shortsword: "../weapons/shortsword.png",
  longsword: "../weapons/longsword.png",
  flaming_longsword: "../weapons/longsword.png",
  greatsword: "../weapons/greatsword.png",
  greatsword_of_wounding: "../weapons/greatsword.png",
  maul: "../weapons/maul.png",
  glaive: "../weapons/glaive.png",
  dagger: "../weapons/dagger.png",
  venomous_dagger: "../weapons/dagger.png",
  battleaxe: "../weapons/battleaxe.png",
  battleaxe_of_fury: "../weapons/battleaxe.png",
  warhammer: "../weapons/warhammer.png",
  thunder_hammer: "../weapons/warhammer.png",
  quarterstaff: "../weapons/quarterstaff.png",
  blessed_quarterstaff: "../weapons/quarterstaff.png",
  rapier: "../weapons/rapier.png",
  frost_brand_rapier: "../weapons/rapier.png",
  scimitar: "../weapons/scimitar.png",
  shocking_scimitar: "../weapons/scimitar.png",
  handaxe: "../weapons/handaxe.png",
  exploding_handaxe: "../weapons/handaxe.png",
  longbow: "../weapons/longbow.png",
  bow_of_accuracy: "../weapons/longbow.png",
  shortbow: "../weapons/shortbow.png",
  silent_bow: "../weapons/shortbow.png",
  mace: "../weapons/mace.png",
  fireball: "spell-fireball.png",
  cure_wounds: "spell-cure-wounds.png",
  counterspell: "../spells/counterspell.png",
  hellish_rebuke: "../spells/hellish_rebuke.png",
  detect_magic: "../spells/detect_magic.png",
  dispel_magic: "../spells/dispel_magic.png",
  divine_smite: "../spells/divine_smite.png",
  eyebite: "../spells/eyebite.png",
  minor_magic: "../spells/minor_magic.png",
  yolandes_regal_presence: "../spells/yolandes_regal_presence.png",
  radiant_smite: "../spells/radiant_smite.png",
  blinding_smite: "../spells/blinding_smite.png",
  staggering_smite: "../spells/staggering_smite.png",
  greater_radiant_smite: "../spells/greater_radiant_smite.png",
  healing_potion: "../consumables/healing_potion.png",
  greater_healing_potion: "../consumables/greater_healing_potion.png",
  superior_healing_potion: "../consumables/superior_healing_potion.png",
  supreme_healing_potion: "../consumables/supreme_healing_potion.png",
  antitoxin: "../consumables/antitoxin.png",
  acid_vial: "../consumables/acid_vial.png",
  alchemists_fire: "../consumables/alchemists_fire.png",
  holy_water: "../consumables/holy_water.png",
  oil_flask: "../consumables/oil_flask.png",
  caltrops: "../consumables/caltrops.png",
  ball_bearings: "../consumables/ball_bearings.png",
  hunting_trap: "../consumables/hunting_trap.png",
  basic_poison: "../consumables/basic_poison.png",
  healers_kit: "../consumables/healers_kit.png",
  fire_granado: "../devices/fire_grenado.png",
  smoke_jar: "../consumables/smoke_jar.png",
  lightning_paper: "../devices/lightning_paper.png",
  greater_lightning_paper: "../devices/greater_lightning_paper.png",
  dash: "../abilities/dash.png",
  dodge: "../abilities/dodge.png",
  hide: "../abilities/hide.png",
  cunning_action_dash: "../abilities/dash.png",
  cunning_action_disengage: "../abilities/cunning_action_disengage.png",
  cunning_action_hide: "../abilities/hide.png",
  action_surge: "../abilities/action_surge.png",
  guard_second_wind: "../abilities/second_wind.png",
  durable_recovery: "../abilities/durable_recovery.png",
  inspiring_leader: "../abilities/inspiring_leader.png",
  shield_master_shove: "../abilities/shield_master_shove.png",
  telekinetic_shove: "../abilities/telekinetic_shove.png",
  weapon_mastery: "../abilities/weapon_mastery.png",
  extra_attack_plus_1: "../abilities/extra_attack_plus_1.png",
  extra_attack_plus_2: "../abilities/extra_attack_plus_2.png",
  lanterna_savant: "../abilities/lanterna_savant.png",
  healing_hands: "../abilities/healing_hands.png",
  celestial_revelation: "../abilities/celestial_revelation.png",
  breath_weapon: "../abilities/breath_weapon.png",
  awakened_breath: "../abilities/awakened_breath.png",
  breath_weapon_black: "../abilities/breath_weapon_black.png",
  breath_weapon_blue: "../abilities/breath_weapon_blue.png",
  breath_weapon_brass: "../abilities/breath_weapon_brass.png",
  breath_weapon_bronze: "../abilities/breath_weapon_bronze.png",
  breath_weapon_copper: "../abilities/breath_weapon_copper.png",
  breath_weapon_gold: "../abilities/breath_weapon_gold.png",
  breath_weapon_green: "../abilities/breath_weapon_green.png",
  breath_weapon_red: "../abilities/breath_weapon_red.png",
  breath_weapon_silver: "../abilities/breath_weapon_silver.png",
  breath_weapon_white: "../abilities/breath_weapon_white.png",
  dwarven_resilience: "../abilities/dwarven_resilience.png",
  dwarven_toughness: "../abilities/dwarven_toughness.png",
  stonecunning: "../abilities/stonecunning.png",
  keen_senses: "../abilities/keen_senses.png",
  fey_ancestry: "../abilities/fey_ancestry.png",
  trance: "../abilities/trance.png",
  high_elf_magic_1: "../abilities/high_elf_magic_1.png",
  gnomish_cunning: "../abilities/gnomish_cunning.png",
  rock_gnome_magic_1: "../abilities/rock_gnome_magic_1.png",
  powerful_build: "../abilities/powerful_build.png",
  large_form: "../abilities/large_form.png",
  clouds_jaunt: "../abilities/clouds_jaunt.png",
  fires_burn: "../abilities/fires_burn.png",
  frosts_chill: "../abilities/frosts_chill.png",
  hills_tumble: "../abilities/hills_tumble.png",
  stones_endurance: "../abilities/stones_endurance.png",
  storms_thunder: "../abilities/storms_thunder.png",
  lucky: "../abilities/lucky.png",
  brave: "../abilities/brave.png",
  halfling_nimbleness: "../abilities/halfling_nimbleness.png",
  naturally_stealthy: "../abilities/naturally_stealthy.png",
  resourceful: "../abilities/resourceful.png",
  skillful: "../abilities/skillful.png",
  versatile: "../abilities/versatile.png",
  adrenaline_rush: "../abilities/adrenaline_rush.png",
  relentless_endurance: "../abilities/relentless_endurance.png",
  otherworldly_presence: "../abilities/otherworldly_presence.png",
  abyssal_legacy_1: "../abilities/abyssal_legacy_1.png",
  chthonic_legacy_1: "../abilities/chthonic_legacy_1.png",
  infernal_legacy_1: "../abilities/infernal_legacy_1.png",
  lineage_elf_high: "../abilities/lineage_elf_high.png",
  lineage_elf_wood: "../abilities/lineage_elf_wood.png",
  lineage_elf_drow: "../abilities/lineage_elf_drow.png",
  lineage_gnome_forest: "../abilities/lineage_gnome_forest.png",
  lineage_halfling_lightfoot: "../abilities/lineage_halfling_lightfoot.png",
  lineage_halfling_stout: "../abilities/lineage_halfling_stout.png",
  second_wind: "../abilities/second_wind.png",
  duelist_flourish: "../abilities/duelist_flourish.png",
  duelist_evasive_step: "../abilities/duelist_evasive_step.png",
  duelist_deadly_precision: "../abilities/duelist_deadly_precision.png",
  champion_execute: "../abilities/champion_execute.png",
  unyielding_stance: "../abilities/unyielding_stance.png",
  rage: "../abilities/rage.png",
  reckless_attack: "../abilities/reckless_attack.png",
  berserker_execute: "../abilities/berserker_execute.png",
  primal_roar: "../abilities/primal_roar.png",
  savage_momentum: "../abilities/savage_momentum.png",
  cunning_action: "../abilities/cunning_action.png",
  reliable_talent: "../abilities/reliable_talent.png",
  umbral_guise: "../abilities/umbral_guise.png",
  ultraviolence: "../abilities/ultraviolence.png",
  rogue_weapon_mastery: "../abilities/rogue_weapon_mastery.png",
  sneak_attack: "../abilities/sneak_attack.png",
  evasion: "../abilities/evasion.png",
  secrets_exposed: "../abilities/secrets_exposed.png",
  dark_presence: "../abilities/dark_presence.png",
  thieves_tools: "../abilities/thieves_tools.png",
  expertise: "../abilities/expertise.png",
  killers_patience: "../abilities/killers_patience.png",
  assassinate: "../abilities/assassinate.png",
  lethal_ambush: "../abilities/lethal_ambush.png",
  low_blow: "../abilities/low_blow.png",
  exploit_weakness: "../abilities/exploit_weakness.png",
  quick_rigging: "../abilities/quick_rigging.png",
  bombmaker: "../abilities/bombmaker.png",
  grenado_formula: "../abilities/grenado_formula.png",
  safe_geometry: "../abilities/safe_geometry.png",
  free_recipe: "../abilities/free_recipe.png",
  master_of_mixtures: "../abilities/master_of_mixtures.png",
  double_rig: "../abilities/double_rig.png",
  catastrophic_charge: "../abilities/catastrophic_charge.png",
  aura_of_protection: "../abilities/aura_of_protection.png",
  aura_of_courage: "../abilities/aura_of_courage.png",
  aura_of_alacrity: "../abilities/aura_of_alacrity.png",
  aura_of_renewal: "../abilities/aura_of_renewal.png",
  sanctified_presence: "../abilities/sanctified_presence.png",
  vow_of_enmity: "../abilities/vow_of_enmity.png",
  relentless_pursuit: "../abilities/relentless_pursuit.png",
  natures_aegis: "../abilities/natures_aegis.png",
  athletic_prowess: "../abilities/athletic_prowess.png",
  legends_surge: "../abilities/legends_surge.png",
  chains_of_vengeance: "../abilities/chains_of_vengeance.png",
  executioners_verdict: "../abilities/executioners_verdict.png",
  glorious_challenge: "../abilities/glorious_challenge.png",
  ability_score_improvement: "../abilities/ability_score_improvement.png",
  keeper_of_souls: "../abilities/keeper_of_souls.png",
  sear_undead: "../abilities/sear_undead.png",
  graves_rebuke: "../abilities/graves_rebuke.png",
  radiance_of_the_dawn: "../abilities/radiance_of_the_dawn.png",
  lanterns_pulse: "../abilities/lanterns_pulse.png",
  warpriest: "../abilities/warpriest.png",
  relentless_advance: "../abilities/relentless_advance.png",
  turn_undead: "../abilities/turn_undead.png",
  harness_divine_power: "../abilities/harness_divine_power.png",
  reapers_shroud: "../abilities/reapers_shroud.png",
  halo_of_daybreak: "../abilities/halo_of_daybreak.png",
  guided_strike: "../abilities/guided_strike.png",
  divine_strike: "../abilities/divine_strike.png",
  sentinel_at_deaths_door: "../abilities/sentinel_at_deaths_door.png",
  judging_flame: "../abilities/judging_flame.png",
  missing_piece: "../abilities/missing_piece.png",
  token_of_passage: "../abilities/token_of_passage.png",
  mark_of_authority: "../abilities/mark_of_authority.png",
  cataclysmic_debt: "../abilities/cataclysmic_debt.png",
  form_of_dread: "../abilities/form_of_dread.png",
  grave_tether: "../abilities/grave_tether.png",
  undead_patrons_spear: "../abilities/undead_patrons_spear.png",
  aura_of_the_grave: "../abilities/aura_of_the_grave.png",
  deathless_form: "../abilities/deathless_form.png",
  book_of_shadows: "../abilities/book_of_shadows.png",
  ominous_insight: "../abilities/ominous_insight.png",
  grimoire_recall: "../abilities/grimoire_recall.png",
  forbidden_transcription: "../abilities/forbidden_transcription.png",
  wicklight: "../abilities/wicklight.png",
  borrowed_flame: "../abilities/borrowed_flame.png",
  light_through_the_cracks: "../abilities/light_through_the_cracks.png",
  the_door_in_the_floor: "../abilities/the_door_in_the_floor.png",
  last_light: "../abilities/last_light.png",
  fiend_hellish_rebuke: "../abilities/fiend_hellish_rebuke.png",
  infernal_resilience: "../abilities/infernal_resilience.png",
  fiend_hellish_rebuke_escalation: "../abilities/fiend_hellish_rebuke_escalation.png",
  fiend_patrons_spear: "../abilities/fiend_patrons_spear.png",
  hurl_through_hell: "../abilities/hurl_through_hell.png",
  cursed_weapon: "../abilities/cursed_weapon.png",
  pact_weapon_extra_attack: "../abilities/pact_weapon_extra_attack.png",
  blade_channel: "../abilities/blade_channel.png",
  lifedrinker_vampiric: "../abilities/lifedrinker_vampiric.png",
  blade_mastery: "../abilities/blade_mastery.png",
  spiral_of_retribution: "../abilities/spiral_of_retribution.png",
  mystic_arcanum_6: "../abilities/mystic_arcanum_6.png",
  mystic_arcanum_7: "../abilities/mystic_arcanum_7.png",
  arcane_recovery: "../abilities/arcane_recovery.png",
  arcane_focus: "../abilities/arcane_focus.png",
  jesters_book_of_shortcuts: "../abilities/jesters_book_of_shortcuts.png",
  dirt_wizard_relentless: "../abilities/dirt_wizard_relentless.png",
  grit_of_the_marginal: "../abilities/grit_of_the_marginal.png",
  truth_in_shards: "../abilities/truth_in_shards.png",
  dirt_wizard_indomitability: "../abilities/dirt_wizard_indomitability.png",
  arcane_armament: "../abilities/arcane_armament.png",
  bonded_accuracy_1: "../abilities/bonded_accuracy_1.png",
  spell_rhythm: "../abilities/spell_rhythm.png",
  bonded_accuracy_2: "../abilities/bonded_accuracy_2.png",
  martial_sigils: "../abilities/martial_sigils.png",
  crescendo_duel: "../abilities/crescendo_duel.png",
  seal_of_mortality: "../abilities/seal_of_mortality.png",
  mortmain: "../abilities/mortmain.png",
  black_aegis: "../abilities/black_aegis.png",
  final_edict: "../abilities/final_edict.png",
  device_acid_paper: "../devices/acid_paper.png",
  device_fire_paper: "../devices/fire_paper.png",
  device_grave_paper: "../devices/grave_paper.png",
  device_greater_acid_paper: "../devices/greater_acid_paper.png",
  device_greater_fire_paper: "../devices/greater_fire_paper.png",
  device_greater_grave_paper: "../devices/greater_grave_paper.png",
  device_greater_lightning_paper: "../devices/greater_lightning_paper.png",
  device_lightning_paper: "../devices/lightning_paper.png",
  device_poison_vial: "../devices/poison_vial.png",
  device_greater_poison_vial: "../devices/greater_poison_vial.png",
  device_acid_grenado: "../devices/acid_grenado.png",
  device_lightning_grenado: "../devices/lightning_grenado.png",
  device_saint_paper: "../devices/saint_paper.png",
  device_tar_vial: "../devices/tar_vial.png",
  device_greater_tar_vial: "../devices/greater_tar_vial.png",
  device_smoke_vial: "../devices/smoke_vial.png",
  device_greater_smoke_vial: "../devices/greater_smoke_vial.png",
  device_makeshift_fan: "../devices/makeshift_fan.png",
  device_thunder_wire: "../devices/thunder_wire.png",
  device_fire_grenado: "../devices/fire_grenado.png",
  device_frost_grenado: "../devices/frost_grenado.png",
  device_grave_dirt_grenado: "../devices/grave_dirt_grenado.png",
  shield: "reaction-shield.png",
  clerics_holy_symbol: "../../assets/icons/holy_symbols/clerics_holy_symbol.png",
  sacral_holy_symbol: "../../assets/icons/holy_symbols/sacral_holy_symbol.png",
  steadfast_holy_symbol: "../../assets/icons/holy_symbols/steadfast_holy_symbol.png",
  symbol_of_red_ruin: "../../assets/icons/holy_symbols/symbol_of_red_ruin.png",
  symbol_of_restless_suffering: "../../assets/icons/holy_symbols/symbol_of_restless_suffering.png",
  wizards_staff: "../weapons/quarterstaff.png",
  staff_of_the_repurposed_flask: "../../assets/icons/wizard_staffs/staff_of_the_repurposed_flask.png",
  staff_of_the_hollow_star: "../../assets/icons/wizard_staffs/staff_of_the_hollow_star.png",
  staff_of_the_winter_hand: "../../assets/icons/wizard_staffs/staff_of_the_winter_hand.png",
  cap_of_vanishing: "../../assets/icons/headwear/cap_of_vanishing.png",
  ring_of_the_sprinter: "../../assets/icons/rings/ring_of_the_sprinter.png",
  ring_of_withdrawal: "../../assets/icons/rings/ring_of_withdrawal.png",
  staff_of_the_adder: "../../assets/icons/wizard_staffs/staff_of_the_adder.png",
  restless_suffering_revivify: "../spells/revivify.png",
  trench_guardian_strike: "../weapons/longsword.png",
  trench_scout_strike: "../weapons/shortsword.png",
  adept_mace: "../weapons/mace.png",
  guard_blade: "../weapons/longsword.png",
});

const WEAPON_BADGES = Object.freeze({
  flaming_longsword: "flame.png",
  venomous_dagger: "poison_bead.png",
  greatsword_of_wounding: "blood_bead.png",
  thunder_hammer: "storm_cloud.png",
  frost_brand_rapier: "snowflake.png",
  bow_of_accuracy: "target.png",
  exploding_handaxe: "lit_bomb.png",
  shocking_scimitar: "lightning_bolt.png",
  blessed_quarterstaff: "praying_hands.png",
  piercing_shortsword: "jagged_x.png",
  battleaxe_of_fury: "bicep.png",
  silent_bow: "psychic_head.png",
});

const CATEGORY_FALLBACKS = Object.freeze({
  weapon: "../weapons/longsword.png",
  spell: "spell-fireball.png",
  consumable: "../consumables/healing_potion.png",
  tactic: "tactic-dash.png",
  ability: "ability-spell-rhythm.png",
  channel_divinity: "ability-spell-rhythm.png",
  device: "device-smoke-vial.png",
  reaction: "reaction-shield.png",
});

export function actionIconCategory(action = {}) {
  if (action.cost === "reaction" || action.economy === "reaction") return "reaction";
  if (action.tags?.weapon || action.iconCategory === "weapon") return "weapon";
  if (action.tags?.spell || action.kind === "spell" || action.iconCategory === "spell") return "spell";
  if (action.tags?.device || action.iconCategory === "device") return "device";
  if (action.tags?.consumable || action.type === "consumable" || action.iconCategory === "consumable") return "consumable";
  if (action.resourceId === "channel_divinity" || action.iconCategory === "channel_divinity") return "channel_divinity";
  if (["dash", "dodge", "hide", "disengage"].includes(action.type) || ["hide", "disengage"].includes(action.actionKind) || action.iconCategory === "tactic") return "tactic";
  return "ability";
}

export function resolveActionIcon(action = {}) {
  const category = actionIconCategory(action);
  const stableId = action.iconId || action.sourceSpellId || action.secondaryChoiceId || action.id;
  const directSpellIcon = category === "spell" && stableId ? `../spells/${stableId}.png` : null;
  const filename = ICONS[stableId] || directSpellIcon || CATEGORY_FALLBACKS[category] || CATEGORY_FALLBACKS.ability;
  return { category, url: new URL(filename, ICON_ROOT).href, isFallback: !ICONS[stableId] && !directSpellIcon };
}

export function createActionIconImage(action, className = "action-icon-art") {
  const resolved = resolveActionIcon(action);
  const stableId = action.iconId || action.sourceSpellId || action.secondaryChoiceId || action.id;
  const container = document.createElement("div");
  container.className = className;
  container.dataset.iconCategory = resolved.category;
  container.dataset.iconFallback = String(resolved.isFallback);

  const base = document.createElement("img");
  base.className = `action-icon-base-layer${action.weaponPair ? " action-icon-primary-weapon-layer" : ""}`;
  base.src = resolved.url;
  base.alt = "";
  base.draggable = false;
  container.append(base);

  if (action.weaponPair?.secondaryIconId) {
    const secondaryResolved = resolveActionIcon({ id: action.weaponPair.secondaryIconId, iconId: action.weaponPair.secondaryIconId, iconCategory: "weapon" });
    const secondary = document.createElement("img");
    secondary.className = "action-icon-secondary-weapon-layer";
    secondary.src = secondaryResolved.url;
    secondary.alt = "";
    secondary.draggable = false;
    container.classList.add(action.weaponPair.mode === "diagonal" ? "is-diagonal-weapon-pair" : "is-corner-weapon-pair");
    container.append(secondary);
  }

  const badgeFilename = WEAPON_BADGES[stableId];
  if (badgeFilename && !action.weaponPair) {
    const badge = document.createElement("img");
    badge.className = "action-icon-badge-layer";
    badge.src = new URL(`./icons/weapon_badges/${badgeFilename}`, import.meta.url).href;
    badge.alt = "";
    badge.draggable = false;
    container.append(badge);
  }
  return container;
}
