// AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
// Generated by: tools/genAreasRegistry.mjs
// Generated at: 2025-12-26T08:46:42.267Z
//
// Source of truth: Ink global tag "MAP_EXITS" (Option 1B).
//
// Coordinates are logical grid positions (not pixels). The renderer scales/centers.
// Convention:
//   [0,0] = current area
//   +x = east, -x = west
//   +y = south, -y = north


export const MINI_MAP_LAYOUTS = {
  "boathouse": {
    "boathouse": [
      0,
      0
    ],
    "dockside": [
      0,
      1
    ]
  },
  "dockside": {
    "boathouse": [
      0,
      -1
    ],
    "dockside": [
      0,
      0
    ],
    "longhouse": [
      1,
      0
    ]
  },
  "longhouse": {
    "dockside": [
      -1,
      0
    ],
    "longhouse": [
      0,
      0
    ]
  }
};

export function getMiniMapLayout(areaId) {
  if (!areaId) return null;
  return MINI_MAP_LAYOUTS[areaId] || null;
}

export default MINI_MAP_LAYOUTS;
