// Reserved frame manifests from the broader animation pass.
// They are intentionally not imported by visualSpike.js while the spike stays sword-only.

export const RESERVED_CHARACTER_FRAMES = {
  rogue: [
    "./assets/protagonist_rogue_move_crop.png",
    "./assets/protagonist_rogue_guard_crop.png",
    "./assets/protagonist_rogue_guard_subtle_crop.png",
    "./assets/protagonist_rogue_attack_windup_crop.png",
    "./assets/protagonist_rogue_attack_intermediate_crop.png",
    "./assets/protagonist_rogue_attack_release_crop.png",
    "./assets/protagonist_rogue_attack_intermediate_crop.png?recovery=1",
    "./assets/protagonist_rogue_hit_crop.png",
    "./assets/protagonist_rogue_collapse_crop.png",
    "./assets/protagonist_rogue_downed_crop.png",
  ],
  warlock: [
    "./assets/protagonist_warlock_move_crop.png",
    "./assets/protagonist_warlock_guard_crop.png",
    "./assets/protagonist_warlock_guard_subtle_crop.png",
    "./assets/protagonist_warlock_attack_windup_crop.png",
    "./assets/protagonist_warlock_attack_intermediate_crop.png",
    "./assets/protagonist_warlock_attack_release_crop.png",
    "./assets/protagonist_warlock_attack_recovery_crop.png",
    "./assets/protagonist_warlock_hit_crop.png",
    "./assets/protagonist_warlock_collapse_crop.png",
    "./assets/protagonist_warlock_downed_crop.png",
  ],
  cleric: [
    "./assets/protagonist_cleric_move_crop.png?cleric-order=4",
    "./assets/protagonist_cleric_guard_crop.png?cleric-order=4",
    "./assets/protagonist_cleric_guard_subtle_crop.png?cleric-order=4",
    "./assets/protagonist_cleric_attack_windup_crop.png",
    "./assets/protagonist_cleric_attack_intermediate_crop.png",
    "./assets/protagonist_cleric_attack_release_crop.png",
    "./assets/protagonist_cleric_attack_recovery_crop.png",
    "./assets/protagonist_cleric_hit_crop.png",
    "./assets/protagonist_cleric_collapse_crop.png",
    "./assets/protagonist_cleric_downed_crop.png",
  ],
  staff: [
    "./assets/protagonist_staff_walk_crop.png",
    "./assets/protagonist_staff_guard_crop.png",
    "./assets/protagonist_staff_guard_subtle.png",
    "./assets/protagonist_staff_cast_windup_crop.png",
    "./assets/protagonist_staff_cast_release_crop.png",
    "./assets/protagonist_staff_cast_intermediate_crop.png",
    "./assets/protagonist_staff_hit_crop.png",
    "./assets/protagonist_staff_collapse_crop.png",
    "./assets/protagonist_staff_downed_crop.png",
  ],
};

export const RESERVED_FOOT_ANCHORS = {
  rogue: [
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
  ],
  warlock: [
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
  ],
  cleric: [
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
  ],
  staff: [
    { x: 0.53, y: 1 },
    { x: 0.52, y: 1 },
    { x: 0.52, y: 1 },
    { x: 0.52, y: 1 },
    { x: 0.48, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.52, y: 1 },
    { x: 0.5, y: 1 },
    { x: 0.5, y: 1 },
  ],
};
